# Generated by Django 4.1.5 on 2023-01-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetid', models.CharField(max_length=100)),
                ('assetname', models.CharField(max_length=100)),
                ('asset_make', models.CharField(max_length=100)),
                ('asset_model', models.CharField(max_length=100)),
                ('slno', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('pmdone', models.DateField(blank=True)),
                ('pmdur', models.IntegerField(null=True)),
                ('pmdue', models.DateField(blank=True)),
                ('pmstat', models.CharField(max_length=100, null=True)),
                ('caldue', models.DateField(blank=True)),
                ('caldur', models.IntegerField(null=True)),
                ('caldone', models.DateField(blank=True)),
                ('calstat', models.CharField(max_length=100, null=True)),
                ('wrstart', models.DateField(blank=True)),
                ('wrend', models.DateField(blank=True)),
                ('warranty', models.CharField(max_length=100, null=True)),
                ('mcstart', models.DateField(blank=True)),
                ('mcend', models.DateField(blank=True)),
                ('amc_cmc', models.CharField(max_length=100, null=True)),
                ('stat', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('CONDEM', 'CONDEM'), ('RETURNED', 'RETURNED'), ('RENTAL', 'RENTAL')], max_length=100)),
                ('doc', models.FileField(null=True, upload_to='media')),
                ('invoice', models.FileField(null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Workbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_id', models.CharField(max_length=100)),
                ('asset_id', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('wo_date', models.DateTimeField(blank=True)),
                ('wo_attended', models.DateTimeField(blank=True)),
                ('wo_done', models.DateTimeField(blank=True)),
                ('status', models.CharField(max_length=100)),
                ('eng_id', models.CharField(max_length=100)),
                ('SR_report', models.FileField(blank=True, null=True, upload_to='media')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
