# Generated by Django 4.1.5 on 2023-01-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSETS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='sign',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
