# Generated by Django 4.1.5 on 2023-01-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSETS', '0002_workbook_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbook',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
