# Generated by Django 4.1.5 on 2023-01-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSETS', '0003_alter_workbook_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbook',
            name='action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workbook',
            name='eng_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workbook',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workbook',
            name='wo_attended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workbook',
            name='wo_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workbook',
            name='wo_done',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
