# Generated by Django 4.1.5 on 2023-01-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSETS', '0005_workbook_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbook',
            name='sign',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
