# Generated by Django 4.1.5 on 2023-01-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSETS', '0006_alter_workbook_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workbook',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workbook',
            name='slno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
