# Generated by Django 4.1.5 on 2023-01-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSETS', '0007_workbook_make_workbook_model_workbook_slno'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='dept',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
