# Generated by Django 4.1.5 on 2023-01-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSETS', '0008_workbook_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='asset_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
