# Generated by Django 4.1.5 on 2023-01-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSETS', '0009_workbook_asset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbook',
            name='action',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
