# Generated by Django 4.1.5 on 2023-01-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSETS', '0010_alter_workbook_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='eng_sign',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
