# Generated by Django 4.1.5 on 2023-01-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSETS', '0011_workbook_eng_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbook',
            name='action',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='workbook',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
