# Generated by Django 4.1.5 on 2023-02-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSETS', '0012_alter_workbook_action_alter_workbook_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='downtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workbook',
            name='rsndtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workbook',
            name='SR_report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
