# Generated by Django 4.1.5 on 2023-02-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSETS', '0013_workbook_downtime_workbook_rsndtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbook',
            name='SR_report',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
