# Generated by Django 4.1.5 on 2023-02-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSETS', '0014_alter_workbook_sr_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbook',
            name='downtime',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
    ]
