# Generated by Django 4.1.5 on 2023-02-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSETS', '0016_alter_workbook_downtime_alter_workbook_rsndtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbook',
            name='downtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workbook',
            name='rsndtime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
